"""
AudioSet (527-class) -> soundscape ecology category crosswalk.
Categories: biophony, anthrophony, geophony, or None (excluded).
Built from the official class_labels_indices.csv used by PANNs/panns_inference.
REVIEW NEEDED: entries marked with # REVIEW were assigned by broad
ontology-range defaults (e.g. all music genres, all generic impact
sounds) rather than individually verified - refine as needed for
your specific Bogota urban/wetland context.
"""

LABEL_CATEGORY = {
    'Speech': 'anthropophony',
    'Male speech, man speaking': None,
    'Female speech, woman speaking': None,
    'Child speech, kid speaking': None,
    'Conversation': None,
    'Narration, monologue': None,
    'Babbling': None,
    'Speech synthesizer': None,
    'Shout': None,
    'Bellow': None,
    'Whoop': None,
    'Yell': None,
    'Battle cry': None,
    'Children shouting': None,
    'Screaming': None,
    'Whispering': None,
    'Laughter': None,
    'Baby laughter': None,
    'Giggle': None,
    'Snicker': None,
    'Belly laugh': None,
    'Chuckle, chortle': None,
    'Crying, sobbing': None,
    'Baby cry, infant cry': None,
    'Whimper': None,
    'Wail, moan': None,
    'Sigh': None,
    'Singing': None,
    'Choir': None,
    'Yodeling': None,
    'Chant': None,
    'Mantra': None,
    'Male singing': None,
    'Female singing': None,
    'Child singing': None,
    'Synthetic singing': None,
    'Rapping': None,
    'Humming': None,
    'Groan': None,
    'Grunt': None,
    'Whistling': None,
    'Breathing': None,
    'Wheeze': None,
    'Snoring': None,
    'Gasp': None,
    'Pant': None,
    'Snort': None,
    'Cough': None,
    'Throat clearing': None,
    'Sneeze': None,
    'Sniff': None,
    'Run': None,
    'Shuffle': None,
    'Walk, footsteps': None,
    'Chewing, mastication': None,
    'Biting': None,
    'Gargling': None,
    'Stomach rumble': None,
    'Burping, eructation': None,
    'Hiccup': None,
    'Fart': None,
    'Hands': None,
    'Finger snapping': None,
    'Clapping': None,
    'Heart sounds, heartbeat': None,
    'Heart murmur': None,
    'Cheering': None,
    'Applause': None,
    'Chatter': None,
    'Crowd': None,
    'Hubbub, speech noise, speech babble': None,
    'Children playing': None,
    'Animal': None,
    'Domestic animals, pets': 'anthropophony',
    'Dog': 'anthropophony',
    'Bark': 'anthropophony',
    'Yip': None,
    'Howl': None,
    'Bow-wow': None,
    'Growling': None,
    'Whimper (dog)': None,
    'Cat': None,
    'Purr': None,
    'Meow': None,
    'Hiss': None,
    'Caterwaul': None,
    'Livestock, farm animals, working animals': 'anthropophony',
    'Horse': None,
    'Clip-clop': None,
    'Neigh, whinny': None,
    'Cattle, bovinae': None,
    'Moo': 'anthropophony',
    'Cowbell': None,
    'Pig': None,
    'Oink': None,
    'Goat': None,
    'Bleat': None,
    'Sheep': None,
    'Fowl': None,
    'Chicken, rooster': None,
    'Cluck': None,
    'Crowing, cock-a-doodle-doo': None,
    'Turkey': None,
    'Gobble': None,
    'Duck': None,
    'Quack': None,
    'Goose': None,
    'Honk': None,
    'Wild animals': 'ny',
    'Roaring cats (lions, tigers)': None,
    'Roar': None,
    'Bird': 'ny',
    'Bird vocalization, bird call, bird song': 'ny',
    'Chirp, tweet': 'biophony',
    'Squawk': 'biophony',
    'Pigeon, dove': 'biophony',
    'Coo': 'biophony',
    'Crow': 'biophony',
    'Caw': 'biophony',
    'Owl': 'biophony',
    'Hoot': 'biophony',
    'Bird flight, flapping wings': None,
    'Canidae, dogs, wolves': 'biophony',
    'Rodents, rats, mice': None,
    'Mouse': None,
    'Patter': None,
    'Insect': 'biophony',
    'Cricket': 'biophony',
    'Mosquito': 'biophony',
    'Fly, housefly': 'biophony',
    'Buzz': 'biophony',
    'Bee, wasp, etc.': 'biophony',
    'Frog': 'biophony',
    'Croak': 'biophony',
    'Snake': None,
    'Rattle': None,
    'Whale vocalization': None,
    'Music': 'anthropophony',
    'Musical instrument': None,
    'Plucked string instrument': None,
    'Guitar': None,
    'Electric guitar': None,
    'Bass guitar': None,
    'Acoustic guitar': None,
    'Steel guitar, slide guitar': None,
    'Tapping (guitar technique)': None,
    'Strum': None,
    'Banjo': None,
    'Sitar': None,
    'Mandolin': None,
    'Zither': None,
    'Ukulele': None,
    'Keyboard (musical)': None,
    'Piano': None,
    'Electric piano': None,
    'Organ': None,
    'Electronic organ': None,
    'Hammond organ': None,
    'Synthesizer': None,
    'Sampler': None,
    'Harpsichord': None,
    'Percussion': None,
    'Drum kit': None,
    'Drum machine': None,
    'Drum': None,
    'Snare drum': None,
    'Rimshot': None,
    'Drum roll': None,
    'Bass drum': None,
    'Timpani': None,
    'Tabla': None,
    'Cymbal': None,
    'Hi-hat': None,
    'Wood block': None,
    'Tambourine': None,
    'Rattle (instrument)': None,
    'Maraca': None,
    'Gong': None,
    'Tubular bells': None,
    'Mallet percussion': None,
    'Marimba, xylophone': None,
    'Glockenspiel': None,
    'Vibraphone': None,
    'Steelpan': None,
    'Orchestra': None,
    'Brass instrument': None,
    'French horn': None,
    'Trumpet': None,
    'Trombone': None,
    'Bowed string instrument': None,
    'String section': None,
    'Violin, fiddle': None,
    'Pizzicato': None,
    'Cello': None,
    'Double bass': None,
    'Wind instrument, woodwind instrument': None,
    'Flute': None,
    'Saxophone': None,
    'Clarinet': None,
    'Harp': None,
    'Bell': None,
    'Church bell': None,
    'Jingle bell': None,
    'Bicycle bell': None,
    'Tuning fork': None,
    'Chime': None,
    'Wind chime': None,
    'Change ringing (campanology)': None,
    'Harmonica': None,
    'Accordion': None,
    'Bagpipes': None,
    'Didgeridoo': None,
    'Shofar': None,
    'Theremin': None,
    'Singing bowl': None,
    'Scratching (performance technique)': None,
    'Pop music': None,
    'Hip hop music': None,
    'Beatboxing': None,
    'Rock music': None,
    'Heavy metal': None,
    'Punk rock': None,
    'Grunge': None,
    'Progressive rock': None,
    'Rock and roll': None,
    'Psychedelic rock': None,
    'Rhythm and blues': None,
    'Soul music': None,
    'Reggae': None,
    'Country': None,
    'Swing music': None,
    'Bluegrass': None,
    'Funk': None,
    'Folk music': None,
    'Middle Eastern music': None,
    'Jazz': None,
    'Disco': None,
    'Classical music': None,
    'Opera': None,
    'Electronic music': None,
    'House music': None,
    'Techno': None,
    'Dubstep': None,
    'Drum and bass': None,
    'Electronica': None,
    'Electronic dance music': None,
    'Ambient music': None,
    'Trance music': None,
    'Music of Latin America': None,
    'Salsa music': None,
    'Flamenco': None,
    'Blues': None,
    'Music for children': None,
    'New-age music': None,
    'Vocal music': None,
    'A capella': None,
    'Music of Africa': None,
    'Afrobeat': None,
    'Christian music': None,
    'Gospel music': None,
    'Music of Asia': None,
    'Carnatic music': None,
    'Music of Bollywood': None,
    'Ska': None,
    'Traditional music': None,
    'Independent music': None,
    'Song': None,
    'Background music': None,
    'Theme music': None,
    'Jingle (music)': None,
    'Soundtrack music': None,
    'Lullaby': None,
    'Video game music': None,
    'Christmas music': None,
    'Dance music': None,
    'Wedding music': None,
    'Happy music': None,
    'Funny music': None,
    'Sad music': None,
    'Tender music': None,
    'Exciting music': None,
    'Angry music': None,
    'Scary music': None,
    'Wind': 'geophony',
    'Rustling leaves': 'geophony',
    'Wind noise (microphone)': None,
    'Thunderstorm': 'geophony',
    'Thunder': 'geophony',
    'Water': 'geophony',
    'Rain': 'geophony',
    'Raindrop': 'geophony',
    'Rain on surface': 'geophony',
    'Stream': 'geophony',
    'Waterfall': None,
    'Ocean': None,
    'Waves, surf': None,
    'Steam': None,
    'Gurgling': None,
    'Fire': None,
    'Crackle': None,
    'Vehicle': 'anthropophony',
    'Boat, Water vehicle': None,
    'Sailboat, sailing ship': None,
    'Rowboat, canoe, kayak': None,
    'Motorboat, speedboat': None,
    'Ship': None,
    'Motor vehicle (road)': 'anthropophony',
    'Car': None,
    'Vehicle horn, car horn, honking': 'anthropophony',
    'Toot': None,
    'Car alarm': 'anthropophony',
    'Power windows, electric windows': None,
    'Skidding': None,
    'Tire squeal': None,
    'Car passing by': 'anthropophony',
    'Race car, auto racing': 'anthropophony',
    'Truck': 'anthropophony',
    'Air brake': 'anthropophony',
    'Air horn, truck horn': 'anthropophony',
    'Reversing beeps': 'anthropophony',
    'Ice cream truck, ice cream van': None,
    'Bus': 'anthropophony',
    'Emergency vehicle': 'anthropophony',
    'Police car (siren)': 'anthropophony',
    'Ambulance (siren)': 'anthropophony',
    'Fire engine, fire truck (siren)': 'anthropophony',
    'Motorcycle': None,
    'Traffic noise, roadway noise': 'anthropophony',
    'Rail transport': None,
    'Train': None,
    'Train whistle': None,
    'Train horn': None,
    'Railroad car, train wagon': None,
    'Train wheels squealing': None,
    'Subway, metro, underground': None,
    'Aircraft': 'anthropophony',
    'Aircraft engine': 'anthropophony',
    'Jet engine': 'anthropophony',
    'Propeller, airscrew': None,
    'Helicopter': 'anthropophony',
    'Fixed-wing aircraft, airplane': None,
    'Bicycle': None,
    'Skateboard': None,
    'Engine': 'anthropophony',
    'Light engine (high frequency)': 'anthropophony',
    "Dental drill, dentist's drill": None,
    'Lawn mower': 'anthropophony',
    'Chainsaw': 'anthropophony',
    'Medium engine (mid frequency)': 'anthropophony',
    'Heavy engine (low frequency)': 'anthropophony',
    'Engine knocking': 'anthropophony',
    'Engine starting': 'anthropophony',
    'Idling': None,
    'Accelerating, revving, vroom': 'anthropophony',
    'Door': None,
    'Doorbell': None,
    'Ding-dong': None,
    'Sliding door': None,
    'Slam': None,
    'Knock': None,
    'Tap': None,
    'Squeak': None,
    'Cupboard open or close': None,
    'Drawer open or close': None,
    'Dishes, pots, and pans': None,
    'Cutlery, silverware': None,
    'Chopping (food)': None,
    'Frying (food)': None,
    'Microwave oven': None,
    'Blender': None,
    'Water tap, faucet': None,
    'Sink (filling or washing)': None,
    'Bathtub (filling or washing)': None,
    'Hair dryer': None,
    'Toilet flush': None,
    'Toothbrush': None,
    'Electric toothbrush': None,
    'Vacuum cleaner': None,
    'Zipper (clothing)': None,
    'Keys jangling': None,
    'Coin (dropping)': None,
    'Scissors': None,
    'Electric shaver, electric razor': None,
    'Shuffling cards': None,
    'Typing': None,
    'Typewriter': None,
    'Computer keyboard': None,
    'Writing': None,
    'Alarm': None,
    'Telephone': None,
    'Telephone bell ringing': None,
    'Ringtone': None,
    'Telephone dialing, DTMF': None,
    'Dial tone': None,
    'Busy signal': None,
    'Alarm clock': None,
    'Siren': 'anthropophony',
    'Civil defense siren': None,
    'Buzzer': None,
    'Smoke detector, smoke alarm': None,
    'Fire alarm': None,
    'Foghorn': None,
    'Whistle': None,
    'Steam whistle': None,
    'Mechanisms': None,
    'Ratchet, pawl': None,
    'Clock': None,
    'Tick': None,
    'Tick-tock': None,
    'Gears': None,
    'Pulleys': None,
    'Sewing machine': None,
    'Mechanical fan': None,
    'Air conditioning': None,
    'Cash register': None,
    'Printer': None,
    'Camera': None,
    'Single-lens reflex camera': None,
    'Tools': None,
    'Hammer': None,
    'Jackhammer': None,
    'Sawing': None,
    'Filing (rasp)': None,
    'Sanding': None,
    'Power tool': None,
    'Drill': None,
    'Explosion': None,
    'Gunshot, gunfire': None,
    'Machine gun': None,
    'Fusillade': None,
    'Artillery fire': None,
    'Cap gun': None,
    'Fireworks': None,
    'Firecracker': None,
    'Burst, pop': None,
    'Eruption': None,
    'Boom': None,
    'Wood': None,
    'Chop': None,
    'Splinter': None,
    'Crack': None,
    'Glass': None,
    'Chink, clink': None,
    'Shatter': None,
    'Liquid': None,
    'Splash, splatter': None,
    'Slosh': None,
    'Squish': None,
    'Drip': None,
    'Pour': None,
    'Trickle, dribble': None,
    'Gush': None,
    'Fill (with liquid)': None,
    'Spray': None,
    'Pump (liquid)': None,
    'Stir': None,
    'Boiling': None,
    'Sonar': None,
    'Arrow': None,
    'Whoosh, swoosh, swish': None,
    'Thump, thud': None,
    'Thunk': None,
    'Electronic tuner': None,
    'Effects unit': None,
    'Chorus effect': None,
    'Basketball bounce': None,
    'Bang': None,
    'Slap, smack': None,
    'Whack, thwack': None,
    'Smash, crash': None,
    'Breaking': None,
    'Bouncing': None,
    'Whip': None,
    'Flap': None,
    'Scratch': None,
    'Scrape': None,
    'Rub': None,
    'Roll': None,
    'Crushing': None,
    'Crumpling, crinkling': None,
    'Tearing': None,
    'Beep, bleep': None,
    'Ping': None,
    'Ding': None,
    'Clang': None,
    'Squeal': None,
    'Creak': None,
    'Rustle': None,
    'Whir': None,
    'Clatter': None,
    'Sizzle': None,
    'Clicking': None,
    'Clickety-clack': None,
    'Rumble': None,
    'Plop': None,
    'Jingle, tinkle': None,
    'Hum': None,
    'Zing': None,
    'Boing': None,
    'Crunch': None,
    'Silence': "silence",
    'Sine wave': None,
    'Harmonic': None,
    'Chirp tone': None,
    'Sound effect': None,
    'Pulse': None,
    'Inside, small room': None,
    'Inside, large room or hall': None,
    'Inside, public space': None,
    'Outside, urban or manmade': None,
    'Outside, rural or natural': None,
    'Reverberation': None,
    'Echo': None,
    'Noise': None,
    'Environmental noise': None,
    'Static': None,
    'Mains hum': None,
    'Distortion': None,
    'Sidetone': None,
    'Cacophony': None,
    'White noise': None,
    'Pink noise': None,
    'Throbbing': None,
    'Vibration': None,
    'Television': None,
    'Radio': None,
    'Field recording': None,
}
